import React from "react";
import ReactDOM from "react-dom";
import AdView from "./Ads/AdView";
// import HomePage from "./HomePage";
import App from "./App";
import CampaignView from "./Campaigns/CampaignView";
import LogIn from "./LogIn";
ReactDOM.render(<CampaignView />, document.getElementById("root"));
//ReactDOM.render(<App />, document.getElementById("root"));
// ReactDOM.render(<AdView />, document.getElementById("root"));
// ReactDOM.render(<LogIn />, document.getElementById("root"));
